### ISSUE TITLE
Max uploaded files size

### ISSUE THREAD

**Issue by GregMage** [XoopsModules25x/tdmdownloads#23]
Hi,

[https://github.com/XoopsModules25x/tdmdownloads/commit/43c4c0c742512d93ffa9e78e606c8c0e83d4d50a](https://github.com/XoopsModules25x/tdmdownloads/commit/43c4c0c742512d93ffa9e78e606c8c0e83d4d50a)

Why do that?

We limit too much things in my opinion!

**Comment by mambax7** [comment]
If you have the option to enter your own number, or select one, then it could work. 
But I didn't test it, so I don't know if you can enter in your own number?

**Comment by GregMage** [comment]
It's not possible to do it

**Comment by GregMage** [comment]
The select has advantages, we should keep it. If we have a file bigger than 10 Mb we can not put it. One could add a "No Limit" entry to correct this problem. Just put a warning that it's risky to leave this option.

**Comment by ggoffy** [comment]
Hi Gregory 

the idea was not to limit to 10 MB

ask 10 person how big a file is with 1048576 bytes. then 9 person will say: I don't know, the size of a file is 1 MB, or 2 MB and so on
nobody uses bytes meanwhile

I always try to make modules for dummies, not for IT experts. And everybody knows, if he looks in explorer to the size of his images: oh, 6 MB, or 8 MB

Therefore our module should have the same "wording", means use MB as indicator for setting. if you want I can extend the listbox to 100 MB, but normally the image (at the moment) have not more than 10 MB

**Comment by ggoffy** [comment]
hi, yes you are right, it is not only for images. what would you suggest: 
- make a loop and create a list until ??
- implement a modal "calculator" and use a textfield
- going back

**Comment by GregMage** [comment]
For the moment I do not know. We must find the best solution. I will look at what I did in my xmdoc module

**Comment by ggoffy** [comment]
an idea:
when I remember back to my beginnings it happened often set a value like here and it didn't work, because I didn't realize immidiatly, that I have also to check also the php setting. 


```
function returnBytes($val) {
    switch (substr($val, -1)) {
        case 'K':
        case 'k':
            return (int)$val * 1024;
        case 'M':
        case 'm':
            return (int)$val * 1048576;
        case 'G':
        case 'g':
            return (int)$val * 1073741824;
        default:
            return $val;
    }
}

$iniPostMaxSize = returnBytes(ini_get('post_max_size'));
$iniUploadMaxFileSize = returnBytes(ini_get('upload_max_filesize'));
$optionMaxsize = [];
for ($i = 1; ; $i = $i+0.5) {
    if ( min($iniPostMaxSize, $iniUploadMaxFileSize) < $i*1048576 ) break;
    $optionMaxsize[$i." MB"] = $i*1048576;
}

$modversion['config'][] = [
    'name'        => 'maxuploadsize',
    'title'       => '_MI_TDMDOWNLOADS_MAXUPLOAD_SIZE',
    'description' => '',
    'formtype'    => 'select',
    'valuetype'   => 'int',
    'default'     => 1048576,
    'options'     => $optionMaxsize
];
```

and in the description for this option we can add a tip for php ini

**Comment by GregMage** [comment]
I find the solution interesting. But it will update the module if we change the value in php.ini to update the drop-down menu in the preferences (we can put a message to explain this).

**Comment by ggoffy** [comment]
no. if you increase the value in php.ini from 32 to 256 MB only the select list will be longer. The value himself you have to change seperately, and I would do it automatically.

**Comment by GregMage** [comment]
Sorry, my explanation was bad. I understood that your system is automatic. To update the module preferences, you must update the module. Xoops does not read xoopsversion.php when you go into module preferences. Xoops only reads xoopsversion.php during installation or update.
To test, change php.ini and go to preferences. The values will not have changed. You update the module and it's ok. Do a little test to see if it's right (I'm not 100% sure) ...

**Comment by GregMage** [comment]
I confirm the problem!

I changed my settings in php.ini like this:
- Max upload size permitted (upload_max_filesize directive in php.ini): 32M
- Max post size permitted (post_max_size directive in php.ini): 256M

I have the following result in the preferences:

![image](https://user-images.githubusercontent.com/16707432/51074248-11fc9600-167d-11e9-8622-3167f9bcd718.png)

Now I update the module and I have:

![image](https://user-images.githubusercontent.com/16707432/51074256-4f612380-167d-11e9-8585-661487a24124.png)

To update the preferences, you have to update the module....

For me it's not a problem but you have to put a text that explains that.

in _MI_TDMDOWNLOADS_MAXUPLOAD_SIZE**DSC**

**Comment by GregMage** [comment]
Add this:

> then update the module to show the new choices

**Comment by ggoffy** [comment]
an update is not necessary

**Comment by GregMage** [comment]
I do not agree with you. You need to update the module to bring up the new entries in the drop-down menu.

try:

> 
> 
> I confirm the problem!
> 
> I changed my settings in php.ini like this:
> 
>     * Max upload size permitted (upload_max_filesize directive in php.ini): 32M
> 
>     * Max post size permitted (post_max_size directive in php.ini): 256M
> 
> 
> I have the following result in the preferences:
> 
> ![image](https://user-images.githubusercontent.com/16707432/51074248-11fc9600-167d-11e9-8622-3167f9bcd718.png)
> 
> Now I update the module and I have:
> 
> ![image](https://user-images.githubusercontent.com/16707432/51074256-4f612380-167d-11e9-8585-661487a24124.png)
> 
> To update the preferences, you have to update the module....
> 
> For me it's not a problem but you have to put a text that explains that.
> 
> in _MI_TDMDOWNLOADS_MAXUPLOAD_SIZE**DSC**

**Comment by ggoffy** [comment]
your are right again *ggg*

**Comment by ggoffy** [comment]
i will add
