### ISSUE TITLE
transformed preference mimetypes from text to array 

### ISSUE THREAD

**Issue by GregMage** [XoopsModules25x/tdmdownloads#24]
Hi,

[https://github.com/XoopsModules25x/tdmdownloads/commit/ff55359a1aa06df0a0f5d001ee20f4812fdf0102](https://github.com/XoopsModules25x/tdmdownloads/commit/ff55359a1aa06df0a0f5d001ee20f4812fdf0102)

Now we can not add new mime type! It is a problem!

The idea of adding a select is good but the list must be created from this one:

[https://github.com/XOOPS/XoopsCore25/blob/master/htdocs/include/mimetypes.inc.php](https://github.com/XOOPS/XoopsCore25/blob/master/htdocs/include/mimetypes.inc.php)

It's my opinion

**Comment by ggoffy** [comment]
Hi Gregory

here it is the same:
If guys know how to add a new mimetype (and understand the system) they are going to xoops_version.php and add it
Non-IT-guys are not understanding it, they need a simple listbox, because a simple typing error can have fatal consequences

but, as I wrote: I try to be a "dummy user" programmer ;-) and to provide modules "for everyone"

> The idea of adding a select is good but the list must be created from this one

I only took the previous list, but we can extend ;-)

**Comment by GregMage** [comment]
The idea is good. I already use a select in my xmdoc module for that.
We must use the list provided by xoops because I do not want the user to change files. Xoops accepts only the same types of this list, you can not add others because xoops will not recognize them.

**Comment by ggoffy** [comment]
> you can not add others because xoops will not recognize them.
 then I would suggest that we make a select which directly use the type array from mimetypes.inc.php ;-)

```
$extensionToMime = include XOOPS_ROOT_PATH . "/include/mimetypes.inc.php";
foreach ( $extensionToMime as $mime ) {
    $optionMime[$mime] = $mime;
}
$modversion['config'][] = [
    'name'        => 'mimetype',
    'title'       => '_MI_TDMDOWNLOADS_MIMETYPE',
    'description' => '_MI_TDMDOWNLOADS_MIMETYPE_DSC',
    'formtype'    => 'select_multi',
    'valuetype'   => 'array',
    'default'     => array('image/gif', 'image/jpeg', 'image/pjpeg', 'image/x-png', 'image/png', 
                            'application/x-zip-compressed', 'application/zip', 'application/rar', 'application/pdf', 'application/x-gtar', 'application/x-tar', 
                            'application/msword', 'application/vnd.ms-excel', 'application/vnd.oasis.opendocument.text', 'application/vnd.oasis.opendocument.spreadsheet', 
                            'application/vnd.oasis.opendocument.presentation', 'application/vnd.oasis.opendocument.graphics', 'application/vnd.oasis.opendocument.chart', 
                            'application/vnd.oasis.opendocument.formula', 'application/vnd.oasis.opendocument.database', 'application/vnd.oasis.opendocument.image', 
                            'application/vnd.oasis.opendocument.text-master'),
    'options'     => $optionMime
];

```

**Comment by GregMage** [comment]
Yes,
https://github.com/XoopsModules25x/tdmdownloads/pull/25

I had already proposed the code ;-)

**Comment by mambax7** [comment]
Ggoffy, if you're OK with his code, then please approve #25 :)

**Comment by mambax7** [comment]
And then close this issue! 
I really like how this collaboration is evolving! That's exactly what we need here! :)

**Comment by ggoffy** [comment]
done
