### ISSUE TITLE
file size

### ISSUE THREAD

**Issue by ggoffy** [XoopsModules25x/tdmdownloads#26]
currently the user have to type in the file. IMO it should be filled in automatically with the real size.
 what do you think?

**Comment by GregMage** [comment]
Yes if we upload a file. But if you put a link, you can not do it automatically. It's complicated to manage ... But not impossible :-)

**Comment by mambax7** [comment]
The module should detect if the file is uploaded, and add the real size.

**Comment by GregMage** [comment]
I will do it

**Comment by GregMage** [comment]
I have a problem!

I thought adding an automatic system compatible with remote files. But for that you have to put the parameter "allow_url_fopen: on". It's a problem for security.

To avoid this it is necessary to make a complex system which gives the size only to the uploaded file and for the others it is necessary to fill by hand ...

Maybe someone to another solution?

**Comment by ggoffy** [comment]
Did you try curl_getinfo($ch, CURLINFO_CONTENT_LENGTH_DOWNLOAD)?

on the other side:
I think in 99% someone is uploading the files.
you can add an info: "if you leave it blank, module tries to estimate size from uploaded file"
then you can add a check during saving/uploading and if blank, get use the filesize from upload

what do you think?

**Comment by GregMage** [comment]
Excellent idea with curl, it works well!
I will propose something with curl.
