### ISSUE TITLE
modify and perm_autoapprove

### ISSUE THREAD

**Issue by ggoffy** [XoopsModules25x/tdmdownloads#27]
if someone modifies a file, it must in any case be accepted seperately. IMO if the user have the permission to autoapprove, also the modification should be automatically accepted.
any remarks?

**Comment by GregMage** [comment]
I agree with you!

**Comment by ggoffy** [comment]
I will do this

**Comment by ggoffy** [comment]
Hi Gregory

modfile.php, line 82
$form = $obj->getForm($lid, false, $donnee = []);

but ind class/downloads.php I find:
public function getForm($donnee = [], $erreur = false, $action = false)

this doesn't match, is this an error (which has no consequences at the moment)?

**Comment by GregMage** [comment]
Hi,
It is not an error. in modfile.php, line 81 and 82:
`        $obj  = $modifiedHandler->create();
        $form = $obj->getForm($lid, false, $donnee = []);`

We use the form that is in "modifiedHandler". It works.
The not-so-logical thing is to have another form than class / downloads.php. 

There must be a reason but I do not remember ...

**Comment by ggoffy** [comment]
a saw it already, was my fault ;-)

**Comment by ggoffy** [comment]
implemented
can someone check and close?

**Comment by GregMage** [comment]
I can not find your files

**Comment by ggoffy** [comment]
I'm a little bit trying to find out what is possible with this "feature" what Michael suggested

if you are going to https://github.com/XoopsModules25x/tdmdownloads can you see then that there my "feature/branch_ggoffy" ?

**Comment by GregMage** [comment]
fine
