### ISSUE TITLE
file list

### ISSUE THREAD

**Issue by ggoffy** [XoopsModules25x/tdmdownloads#30]
Hi 

in the file list (search.php) at the moment there is on the left side only a link for downloading.
I would like to move it to right side and add
- a link for showing details (would be the same as clicking on download title)
- a link for editing/modifying, if the user have the permission for this action

any ideas?

**Comment by GregMage** [comment]
I find your idea very well

**Comment by ggoffy** [comment]
done

**Comment by ggoffy** [comment]
Hi Gregory, can I close now?

**Comment by GregMage** [comment]
Yes
