### ISSUE TITLE
Why???

### ISSUE THREAD

**Issue by GregMage** [XoopsModules25x/tdmdownloads#38]
Why are the following "Pull Requests" canceled?

https://github.com/XoopsModules25x/tdmdownloads/pull/31

https://github.com/XoopsModules25x/tdmdownloads/pull/29

**Comment by ggoffy** [comment]
I didn't delete

**Comment by GregMage** [comment]
I think it's this branch:

https://github.com/XoopsModules25x/tdmdownloads/tree/feature/branch_ggoffy

This did not keep the changes between the beginning of your branch and the merger.

**Comment by ggoffy** [comment]
I dont know because I do not understand this "feature" till now. But Michael sent a more detailed description. I have to study it.
If I was really the guilty guy please excuse

**Comment by mambax7** [comment]
we can delete the branches, so there is no problem, as long as they are not committed to the "master"
