### ISSUE TITLE
Download image and getImgListAsArray

### ISSUE THREAD

**Issue by ggoffy** [XoopsModules25x/tdmdownloads#60]
Hi

we have a problem with the file mimetypes. we provide now all mimetype which are defined in mimetypes.inc.php.
in class/downloads.php we have a dropdown for download logo. for the list of the select class/xoopslists.php function getImgListAsArray read the file from directory uploads/tdmdownloads/images/shots
but getImgListAsArray put not all image type on the list
`if (preg_match('/(\.gif|\.jpg|\.png)$/i', $file)) {`

now you can uplod e.g. jpeg files if allowed in module preferences but they will be not shown in the list.

we can ask for core change, but this will take time

what doing? going back to defined list of allowed mimetypes?

**Comment by GregMage** [comment]
Hi,

He has no problem. The changes made do not concern the images mentioned.

Today it does not depend on preferences (mimetype preferences only apply to download)

in admin/download.php:
`                $uploader_2 = new \XoopsMediaUploader($uploaddir_shots, [
                    'image/gif',
                    'image/jpeg',
                    'image/pjpeg',
                    'image/x-png',
                    'image/png',
                ], $helper->getConfig('maxuploadsize'), null, null);`

**Comment by ggoffy** [comment]
you allow jpeg but getImgListAsArray doesn't show jpeg

**Comment by GregMage** [comment]
I understood! It's not the changes we've made that are responsible for that.
It's a problem xoops. It must change:
`preg_match('/(\.gif|\.jpg|\.png)$/i', $file)`

with
`preg_match('/(\.gif|\.jpg|\.jpeg|\.png)$/i', $file)`

**Comment by ggoffy** [comment]
yes, but this is core. and getImgListAsArray should IMO handle all image types

how to solve meanwhile: I think the best would be do allow at the moment only this 3 types of getImgListAsArray

**Comment by GregMage** [comment]
Yes we can. This problem has never been raised since this module exists ... But it is a problem. You have to post the problem here:

[https://github.com/XOOPS/XoopsCore25/issues](https://github.com/XOOPS/XoopsCore25/issues)

xoops 2.5.10 should fix this problem. Maybe Richard can give us another solution.

**Comment by ggoffy** [comment]
I contacted Richard by mail ;-)

**Comment by geekwright** [comment]
Yes, that is broken. I'll get a fix out soon. Thanks!

**Comment by geekwright** [comment]
This should be fixed when https://github.com/XOOPS/XoopsCore25/pull/620 is merged.

I'm planning out the 2.5.10 release right now, so you caught this just in time.

**Comment by ggoffy** [comment]
perfect, thank you very much
