### ISSUE TITLE
Problem with file size

### ISSUE THREAD

**Issue by GregMage** [XoopsModules25x/tdmdownloads#61]
in class/Downloads.php we have that:

`$typeArray = [ _AM_TDMDOWNLOADS_BYTES  => '[' . _AM_TDMDOWNLOADS_BYTES . ']',
                            _AM_TDMDOWNLOADS_KBYTES => '[' . _AM_TDMDOWNLOADS_KBYTES . ']',
                            _AM_TDMDOWNLOADS_MBYTES => '[' . _AM_TDMDOWNLOADS_MBYTES . ']',
                            _AM_TDMDOWNLOADS_GBYTES => '[' . _AM_TDMDOWNLOADS_GBYTES . ']',
                            _AM_TDMDOWNLOADS_TBYTES => '[' . _AM_TDMDOWNLOADS_TBYTES . ']',
                        ];`
This code is very bad (I wrote this a long time ago).
Example with: 

> define('_AM_TDMDOWNLOADS_KBYTES', '??');

in French:
> define('_AM_TDMDOWNLOADS_KBYTES', 'ko');

in Fnglish

> define('_AM_TDMDOWNLOADS_KBYTES', 'kB');

The size value saved in the database is created like this:

`$obj->setVar('size', $size . ' ' . _AM_TDMDOWNLOADS_KBYTES);`

The value in the database is related to the language.
If I have a multilingual site, I record in English and a user reads the site in French ... The size is displayed in English.

The current code is useful for displaying the size but it will cause problems.

We have to change the code but this has consequences for the data already inserted in the database.

I will propose a code that corrects the problem and allows the old data that is in the database to work.

**Comment by ggoffy** [comment]
hi. I suggest to do someting similar like in the preferences: storing always in bytes, but showing then e.g. in kb or MB (depending on the size)
for cleaning/adapting existing values we need a proper function in onupdate.php
