### ISSUE TITLE
Problem with preference "Max uploaded files size"

### ISSUE THREAD

**Issue by GregMage** [XoopsModules25x/tdmdownloads#62]
If we put "Max upload size" at 2000 MB the system will create 2000 entries in the drop-down menu. This slows down the preferences

**Comment by ggoffy** [comment]
yes, thats true, but 
- I don't think that this is reality
- maybe it slow done loading of preferences. it is important that the module works fast in the real use, setting of prefences will be made one or two times

**Comment by GregMage** [comment]
I did tests and it's a problem. In addition to having a drop-down menu with over 1000 entries is not practical.

Although 90% of users will not be affected by this problem, we can not ignore it.

I will propose a patch, you look if you find it well.

**Comment by GregMage** [comment]
I just sent my code. I find interesting to do that.
