### ISSUE TITLE
TDMDOWNLOAD extra fields

### ISSUE THREAD

**Issue by Heyula** [XoopsModules25x/tdmdownloads#71]
a picture of a program as well as the icon of the program I want.

![123](https://user-images.githubusercontent.com/5504159/52180466-826b8280-27f7-11e9-8be4-2352880f140e.jpg)

we can make more beautiful themes.

**Comment by GregMage** [comment]
t's a big change, I do not know if it's a thing to do.

**Comment by Heyula** [comment]
Yes, but it would be very nice.

Demo:
http://demo.erenyumak.com/

![1](https://user-images.githubusercontent.com/5504159/52874903-f6951700-3163-11e9-8afd-f152e600de71.jpg)
![2](https://user-images.githubusercontent.com/5504159/52874905-f6951700-3163-11e9-8343-d0fc1f5184d3.jpg)
