### ISSUE TITLE
Template admin pages

### ISSUE THREAD

**Issue by aerograf** [XoopsModules25x/tdmdownloads#75]
For some reason, templates for pages and admin panel are not called. That is, in all tabs, except for the buttons, there is nothing else.
Buttons also, except for the main page, do not work.
If you replace the line:
`$ GLOBALS ['xoopsTpl'] -> assign ('themeForm', $ form->render ());`
on
` $ GLOBALS ['xoopsTpl'] -> assign ('themeForm', $ form->display ());`
something starts to work ...
What could be the problem?

**Comment by ggoffy** [comment]
hi
can it be that you have in your theme the old templates from tdmdowloads?
please replace all template from {xoops_root}/themes/{yourtheme}/modules/tdmdownloads/ by the templates from new tdmdownloads

**Comment by aerograf** [comment]
Excluded. Installation from scratch. Especially in 1.66 admin templates were not.
I checked everything already ...

**Comment by ggoffy** [comment]
this is what I mean. xbootstrap from xoops 2.5.10 is not compatible with new tdmdownloads. delete {xoops_root}/themes/{yourtheme}/modules/tdmdownloads or replace all template from {xoops_root}/themes/{yourtheme}/modules/tdmdownloads/ by the templates from new tdmdownloads

**Comment by aerograf** [comment]
With the replacement of templates did not work.
It turned out to be corrected only by replacing the line:
`$ templateMain = 'tdmdownloads_admin_about.tpl';`
on
`$ templateMain = 'admin / tdmdownloads_admin_about.tpl';`
etc.
How well I do not know, but it works.

**Comment by aerograf** [comment]
To eliminate such problems, you need to make changes to the admin files or attach a description to the installation so that the user can make changes.
