### ISSUE TITLE
pictures don't show

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/tdmdownloads#86]
Tested with XOOPS 2.5.11-Beta2 latest version and tdmdownloads from here:
https://github.com/mambax7/tdmdownloads

As you can see bellow, pictures don't show:

![image](https://user-images.githubusercontent.com/4613970/128362130-afa23b45-07c5-4988-87bd-bb1c287b757e.png)

pictures URL:
/uploads/tdmdownloads/images/shots/blank.png
___

My config:

Apache/2.4.18 (Ubuntu)
PHP version	7.4.9
MySQLi extension	mysqlnd 7.4.9

**Comment by mambax7** [comment]
It should be now fixed:
![image](https://user-images.githubusercontent.com/613686/128654470-ce5c3b96-2489-4ce7-8a73-e3f7a8a5e157.png)
