### ISSUE TITLE
Clone Module

### ISSUE THREAD

**Issue by Heyula** [XoopsModules25x/tdmdownloads#91]
Is it very difficult to add cloning feature to this module? 

We can use it for other purposes with the additional fields management in the module.

**Comment by mambax7** [comment]
What other purposes would you see? Can you give some examples? 
About cloning itself, I'm not sure, I would need to look into it...

**Comment by mambax7** [comment]
I've added cloning, but you'll have to test if it works for you:
https://github.com/mambax7/tdmdownloads

Please reports back any bugs or issues
