### ISSUE TITLE
[tdmdownloads] - Module path missing in index module front page

### ISSUE THREAD

**Issue by jorgenqv** [XoopsModules25x/tdmdownloads#92]
```
TDMDownloads 2.1.0 Beta 1 (2021-08-08)
XOOPS Version: 2.5.10 and 2.5.11 Beta2 current master downloaded from Github (Dec-31-2021)
PHP Version:  	7.4.27 and  8.0.14
mySQL Version:  5.5.5-10.3.32-MariaDB-1:10.3.32+maria~focal
Server API: 	cgi-fcgi
OS:  Linux (Host one.com)
```

**Issue**
Links in the top of the module index page is missing variable $mod_url so the top header image /assets/images/logo-en.gif is not shown and links is not working. The links is missing the path /modules/tdmdownloads/

**Steps to reproduce**
1. Install module TDMDownloads 2.1.0 Beta 1 (2021-08-08) from Github
2. Go to Admin and add some categories and downloads
3. Go to module front index page

**Expected behaviour**
That the top logo-en.gif should be visible and links working.

One workaround is to edit tdmdownloads/templates/tdmdownloads_idex.tpl and replace all  <{$mod_url}> with the correct url.

Other views module pages than index.php like viewcat.php the mod_url seems to work fine. 

**Other information**
Debug reporting Error tab in PHP 8.0.14: Lots of 
Warning: Undefined array key "mod_url" in file in file /path/xoops_data/caches/smarty_compile/e897619a-tdmdownloads-theme-default^%%CE^CEC^CECE7D3F%%db%3Atdmdownloads_index.tpl.php line 10
repeated another 6 times for line 11, 29, 36, 46, 79 and 80.
Deprecated
Queries
0.000141 - SET SQL_BIG_SELECTS = 1
0.000901 - SELECT * FROM config WHERE (`conf_modid` = '0' AND `conf_catid` = '1') ORDER BY conf_order ASC
0.000329 - SELECT sess_data, sess_ip FROM session WHERE sess_id = '412d15bb0802092ffcb52e47e9fbe1f3'
0.000413 - SELECT * FROM users WHERE uid = '1'
0.000299 - SELECT * FROM modules WHERE dirname = 'tdmdownloads'
0.000973 - SELECT * FROM config WHERE (`conf_modid` = '16') ORDER BY conf_order ASC
0.000228 - DELETE FROM protector_access WHERE expire < UNIX_TIMESTAMP()
0.000306 - SELECT COUNT(*) FROM protector_access WHERE ip='78.82.202.13' AND request_uri='/jorgen/xoops/modules/tdmdownloads/'
0.000216 - SELECT COUNT(*) FROM protector_access WHERE ip='78.82.202.13'
0.000285 - INSERT INTO protector_access SET ip='78.82.202.13', request_uri='/jorgen/nyxoops/modules/tdmdownloads/', expire=UNIX_TIMESTAMP()+'60'
0.004325 - SELECT * FROM config WHERE (`conf_modid` = '0' AND `conf_catid` = '5') ORDER BY conf_order ASC
0.000243 - SELECT COUNT(*) FROM banner
0.000228 - SELECT * FROM banner LIMIT 0, 1
0.000266 - UPDATE banner SET impmade = 323 WHERE bid = 1
0.000367 - SELECT * FROM config WHERE (`conf_modid` = '0' AND `conf_catid` = '3') ORDER BY conf_order ASC
0.001719 - SELECT DISTINCT gperm_itemid FROM group_permission WHERE gperm_name = 'block_read' AND gperm_modid = 1 AND gperm_groupid IN (1,2)
0.001349 - SELECT b.* FROM newblocks b, block_module_link m WHERE m.block_id=b.bid AND b.isactive=1 AND b.visible=1 AND m.module_id IN (0,16) AND b.bid IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,30,23,24,25,26,29,28,27,56,31,32,33,34,35,59,52,47,50,57,48,46,49,58,53,36,37,38,39,40,51,54,43,42,41,44,45,55,60,72,74,73,75,76,61,64,63,62,65,68,70,71,67,69,66) ORDER BY b.weight, m.block_id
0.000660 - SELECT * FROM modules WHERE (`hasmain` = '1' AND `isactive` = '1' AND `weight` > '0') ORDER BY weight ASC, mid ASC
0.000545 - SELECT * FROM group_permission WHERE (`gperm_name` = 'module_read' AND `gperm_modid` = '1' AND (`gperm_groupid` = '1' OR `gperm_groupid` = '2'))
0.000278 - SELECT * FROM modules WHERE dirname = 'news'
0.000639 - SELECT * FROM config WHERE (`conf_modid` = '5') ORDER BY conf_order ASC
0.006716 - SELECT f.*, s.tpl_source FROM tplfile f LEFT JOIN tplsource s ON s.tpl_id=f.tpl_id WHERE (`tpl_tplset` = 'default' AND `tpl_file` = 'system_block_mainmenu.tpl') ORDER BY tpl_refid
0.000614 - SELECT COUNT(*) FROM `priv_msgs` WHERE (`read_msg` = '0' AND `to_userid` = '1')
0.000729 - SELECT f.*, s.tpl_source FROM tplfile f LEFT JOIN tplsource s ON s.tpl_id=f.tpl_id WHERE (`tpl_tplset` = 'default' AND `tpl_file` = 'system_block_user.tpl') ORDER BY tpl_refid
0.000706 - SELECT u.uid, u.uname, u.email, u.user_viewemail, u.user_avatar, g.name AS groupname FROM groups_users_link l LEFT JOIN users u ON l.uid=u.uid LEFT JOIN groups g ON l.groupid=g.groupid WHERE g.group_type='Admin' ORDER BY l.groupid, u.uid
0.000720 - SELECT f.*, s.tpl_source FROM tplfile f LEFT JOIN tplsource s ON s.tpl_id=f.tpl_id WHERE (`tpl_tplset` = 'default' AND `tpl_file` = 'system_block_siteinfo.tpl') ORDER BY tpl_refid
0.000901 - SELECT * FROM group_permission WHERE (`gperm_name` = 'tdmdownloads_view' AND `gperm_modid` = '16' AND (`gperm_groupid` = '1' OR `gperm_groupid` = '2'))
0.000277 - SELECT * FROM `tdmdownloads_downloads` WHERE (`status` != '0' AND `cid` IN (1,2))
0.000285 - SELECT * FROM `tdmdownloads_cat` WHERE (`cat_cid` IN (1,2)) ORDER BY cat_weight ASC, cat_title ASC
0.000220 - SELECT * FROM smiles
0.000219 - SELECT * FROM `tdmdownloads_downloads` WHERE (`status` != '0' AND `cid` IN (1,2)) ORDER BY date DESC LIMIT 0, 5
0.000192 - SELECT * FROM `tdmdownloads_downloads` WHERE (`status` != '0' AND `cid` IN (1,2)) ORDER BY hits DESC LIMIT 0, 5
0.000180 - SELECT * FROM `tdmdownloads_downloads` WHERE (`status` != '0' AND `cid` IN (1,2)) ORDER BY rating DESC LIMIT 0, 5
0.000177 - SELECT * FROM `tdmdownloads_downloads` WHERE (`status` != '0' AND `cid` IN (1,2)) ORDER BY date DESC LIMIT 0, 10
0.000601 - SELECT * FROM group_permission WHERE (`gperm_name` = 'tdmdownloads_download' AND `gperm_modid` = '16' AND (`gperm_groupid` = '1' OR `gperm_groupid` = '2'))
0.000564 - SELECT * FROM group_permission WHERE (`gperm_name` = 'tdmdownloads_download_item' AND `gperm_modid` = '16' AND (`gperm_groupid` = '1' OR `gperm_groupid` = '2'))
0.000332 - SELECT * FROM xoopsnotifications WHERE (`not_modid` = '16' AND `not_category` = 'global' AND `not_uid` = '1') ORDER BY not_id ASC
0.000288 - SELECT * FROM modules WHERE mid = 16
0.001462 - SELECT f.*, s.tpl_source FROM tplfile f LEFT JOIN tplsource s ON s.tpl_id=f.tpl_id WHERE (`tpl_tplset` = 'default' AND `tpl_file` = 'tdmdownloads_index.tpl') ORDER BY tpl_refid
0.000711 - SELECT f.*, s.tpl_source FROM tplfile f LEFT JOIN tplsource s ON s.tpl_id=f.tpl_id WHERE (`tpl_tplset` = 'default' AND `tpl_file` = 'system_notification_select.tpl') ORDER BY tpl_refid
Total: 40
Blocks
Login: Not cached
Main Menu: Not cached
User Menu: Not cached
Site Info: Not cached
Total: 4
Extra
Included files: 210 files
Memory usage: 1415760 bytes
Timers
XOOPS took 0.149 seconds to load.
XOOPS Boot took 0.012 seconds to load.
Module init took 0.004 seconds to load.
XOOPS output init took 0.068 seconds to load.
Module display took 0.005 seconds to load.
Page rendering took 0.058 seconds to load.

**Comment by mambax7** [comment]
@jorgenqv,

Thank you for testing the TdmDownloads module, and for reporting the issue. 

There is a newer version in my repository, so could you please download it and see if there are still issues? 
 
https://github.com/mambax7/tdmdownloads

I'm in process of updating a lot of modules for PHP 8, so if you want to test some of them, please take a look there. 

Also, Goffy has just updated several of his "wg" modules:
https://xoops.org/modules/newbb/viewtopic.php?post_id=366376

You can find them here here in https://github.com/XoopsModules25x/

Once again, thank you and please keep us posted...

Michael

**Comment by jorgenqv** [comment]
Tried the newer Version 2.1 Beta 3 from Nov 3, 2021 with the same issue as Beta 1 Aug 8, 2021, no top image and links missing mod_url.

**Comment by jorgenqv** [comment]
Ah, did some more digging and found a missing row at the end of tdmdownloads/index.php row 279-280:

$xoTheme->addMeta('meta', 'keywords', $keywords);
require XOOPS_ROOT_PATH . '/footer.php';

Insert row:

$xoTheme->addMeta('meta', 'keywords', $keywords);
$GLOBALS['xoopsTpl']->assign('mod_url', XOOPS_URL . '/modules/' . $moduleDirName);
require XOOPS_ROOT_PATH . '/footer.php';

Looks to fix the problem and works fine on my PHP8 / Xoops 2.5.11 site now. No errors :-)  Also tested on Xoops 2.5.10 with PHP 7.4.27
